python3 ../../../main_pretrain.py \
    --dataset imagenet \
    --subset_class_num 10 \
    --backbone resnet50 \
    --data_dir /data1/1K_New \
    --train_dir train \
    --val_dir val \
    --max_epochs 500 \
    --gpus 0,1 \
    --accelerator gpu \
    --strategy ddp \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.4 \
    --classifier_lr 0.1 \
    --weight_decay 1e-5 \
    --batch_size 512 \
    --num_workers 4 \
    --crop_size 64 \
    --brightness 0.8 \
    --contrast 0.8 \
    --saturation 0.8 \
    --hue 0.2 \
    --gaussian_prob 0.0 0.0 \
    --num_crops_per_aug 1 1 \
    --name simclr-2GPU \
    --project simclr-test-MUL-GPU \
    --entity mlbrl \
    --wandb \
    --save_checkpoint \
    --method simclr \
    --temperature 0.2 \
    --proj_hidden_dim 2048 \
    --proj_output_dim 256
