OUTPUT_DIR: "/data1/downstream_tasks/detectron2/byol+loss_f-lr0.3-beta_cosine_V2_0.9-resnet50-imagenet-1000ep-mask-cropping0.3-mask-pooling-ep=99_pascal2"
# INPUT:
#   RANDOM_FLIP: "horizontal" #["horizontal, "vertical", "none"]
#   CROP: True
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    LOSS_WEIGHT: 0.2
  WEIGHTS: "/data1/solo/downstream/object_detection/detect_weight/byol+loss_f-lr0.3-beta_cosine_V2_0.9-resnet50-imagenet-1000ep-mask-cropping0.3-mask-pooling-ep=99.pkl"
  #WEIGHTS: "/data/downstream_tasks/mscrl_200epc_detectron.pkl"
  #WEIGHTS: "/data/downstream_tasks/Baseline_detectron_model.pkl"
  #WEIGHTS: "/data/downstream_tasks/smclr_200_baseline.pkl"
  ROI_HEADS:
    NAME: "Res5ROIHeadsExtraNorm"
    NUM_CLASSES: 20
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
    ######## for rn50-w2 ###########
    # WIDTH_PER_GROUP: 128
    # RES2_OUT_CHANNELS: 512
    # STEM_OUT_CHANNELS: 128
    ######## for rn50-w3 ###########
    # WIDTH_PER_GROUP: 192
    # RES2_OUT_CHANNELS: 768
    # STEM_OUT_CHANNELS: 192
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  FORMAT: "RGB" # torchvision models take RGB input
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
TEST:
  PRECISE_BN:
    ENABLED: True
SOLVER:
  #STEPS: (18000, 22000, 24000)
  STEPS: ( 18000, 21000)
  MAX_ITER: 24000
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.333
  #IMS_PER_BATCH: 16
  BASE_LR: 0.02