python3 ../../../main_pretrain.py \
    --dataset imagenet_with_mask \
    --backbone resnet50_MNCRL \
    --data_dir /data1/1K_New \
    --train_dir train \
    --val_dir val \
    --mask_dir train_binary_mask_by_USS \
    --max_epochs 100 \
    --gpus 0 \
    --accelerator ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --classifier_lr 0.3 \
    --weight_decay 3e-5 \
    --batch_size 512 \
    --num_workers 16 \
    --crop_style Mask_boxes_0.3 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 1.0 0.1 \
    --solarization_prob 0.0 0.2 \
    --num_crops_per_aug 1 1 \
    --name imagenet-mocov2plus+pixel_level_contrastive_new_background_momentum-dim2048-100ep-batch512-resnet50 \
    --project MFPLCL \
    --entity mlbrl \
    --wandb \
    --save_checkpoint \
    --method moco_MPLCL \
    --proj_hidden_dim 2048 \
    --pixel_output_dim 2048 \
    --queue_size 65536 \
    --temperature 0.1 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 0.999 \
    --momentum_classifier \
    --channels_last \
    --checkpoint_dir /data1/MPLCL_ckpt \
