python3 ../../../main_pretrain.py \
    --dataset imagenet \
    --backbone resnet50 \
    --data_dir /data1/1K_New \
    --train_dir train \
    --val_dir val \
    --subset_rate 0.1 \
    --max_epochs 100 \
    --gpus 2 \
    --accelerator gpu \
    --strategy ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.001 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --weight_decay 1e-6 \
    --batch_size 512 \
    --num_workers 4 \
    --brightness 0.8 \
    --contrast 0.8 \
    --saturation 0.8 \
    --hue 0.2 \
    --num_crops_per_aug 2 \
    --name simclr-100ep-imagenet10% \
    --project solo_MPLRCL \
    --entity mlbrl \
    --wandb \
    --save_checkpoint \
    --checkpoint_dir /data1/MPLCL_ckpt \
    --method simclr \
    --temperature 0.2 \
    --proj_hidden_dim 2048 \
